version: '3.8'
services:
  fluentd_acb:
    image: puzolmongol/fluentd_acb:latest
    container_name: fluentd_acb
    ports: 
      - 24224:24224
    restart: always  
      
#docker run -it -p 24224:24224 -v C:\DEVLAB\PRUEBA_ACB\FLUENTD\fluent.conf:/fluentd/etc/demo.conf -e FLUENTD_CONF=demo.conf puzolmongol/fluentd_acb:latest   